permalink: /posts/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-github-metadata
  - jemoji

repository: mmeyer2k/mmeyer2k.github.io

url: http://mmeyer2k.github.io

highlighter: rouge

logo: /images/xor.png

markdown: kramdown

analytics: UA-40063960-2

encoding: UTF-8