permalink: /posts/:title

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

github: mmeyer2k

url: http://mmeyer2k.github.io

highlighter: rouge

logo: /images/xor.png

markdown: kramdown

analytics: UA-40063960-2

encoding: UTF-8

just-comments-apikey: 7e9823619cdb8edf52c4edbf6b521b75